Resolve Warmup Error
triton-inference-server/identity_backend pull request #15
Opened 2021-12-07 00:50 UTC by dyastremsky

This PR resolves the "Server not ready" error received when a model with warmup enabled in the config is loaded. This backend relies on a shared function, SupportFirstDimBatching, to get whether the first dimension can be batched. However, that function is intended to only be used when the server is ready. So it does not work for the warmup function, since the models are still being loaded.

Since the issue is isolated to this backend, this PR aims to fix the issue while keeping the scope within this backend. I modified the identity backend to handle the expected exception. In the case of warmup, batching does not matter, so the code will run the warmup requests and load the model. If the model or server is unavailable for a regular request, it will return an error during the run phase (SupportFirstDimBatching was never meant to be used as a test for model availability).

2021-12-07 02:11 UTC, tanmayv25 commented
@dyastremsky  This issue first came up with the stateful_backend which also uses the SupportFirstDimBatching and whatever we propose here would be picked up by other SupportFirstDimBatching  users. A couple of questions and suggestions for your solution.

1. Why not use something like this for detecting directly whether batching is supported or not?
https://github.com/triton-inference-server/tensorrt_backend/blob/main/src/tensorrt.cc#L1471
This is exactly what we do in triton core anyways: https://github.com/triton-inference-server/server/blob/main/src/core/tritonserver.cc#L1954.
This logic can be moved to backend utilities instead of Triton core. @GuanLuo what do you think?

2. If for some reason we do want to keep it in the core, instead of handling and ignoring the error I would recommend adding a flag in TRITONBACKEND_Request object which marks it as a warmup request. For the warmup requests, backend developers can ignore SupportFirstDimBatching call and other associated logic.

2021-12-07 02:15 UTC, tanmayv25 commented on src/identity.cc
err object must be destructed if TRITONSERVER_ErrorCode(err) == TRITONSERVER_ERROR_UNAVAILABLE

2021-12-07 02:16 UTC, CoderHam requested changes

2021-12-07 02:16 UTC, CoderHam commented on src/identity.cc
> +  if (err != nullptr && TRITONSERVER_ErrorCode(err) != TRITONSERVER_ERROR_UNAVAILABLE){
Add space before "{" / run formatter

2021-12-07 02:16 UTC, CoderHam commented on src/identity.cc
> +  if (err != nullptr && TRITONSERVER_ErrorCode(err) != TRITONSERVER_ERROR_UNAVAILABLE){
Add brackets around `err != nullptr` and `TRITONSERVER_ErrorCode(err) != TRITONSERVER_ERROR_UNAVAILABLE`

2021-12-07 18:06 UTC, GuanLuo commented
@tanmayv25  `TRITONSERVER_ServerModelBatchProperties` is used in GRPC / HTTP server frontend to handle classification extension so it is needed in the core. I think the point here is that `BackendModel::SupportsFirstDimBatching(bool* supports)` shouldn't call into the server API as the API may not work properly unless the server is running. FYI, warmup does have batching functionality, so I don't think the current change is a proper fix

2021-12-07 18:31 UTC, tanmayv25 commented
> @tanmayv25 `TRITONSERVER_ServerModelBatchProperties` is used in GRPC / HTTP server frontend to handle classification extension so it is needed in the core. I think the point here is that `BackendModel::SupportsFirstDimBatching(bool* supports)` shouldn't call into the server API as the API may not work properly unless the server is running. FYI, warmup does have batching functionality, so I don't think the current change is a proper fix

Exactly. SupportsFirstDimBatching can be changed to directly read the max_batch_size from the model config and return true if it is non-zero. @dyastremsky  Does that make sense?

2021-12-07 18:55 UTC, dyastremsky commented
> > @tanmayv25 `TRITONSERVER_ServerModelBatchProperties` is used in GRPC / HTTP server frontend to handle classification extension so it is needed in the core. I think the point here is that `BackendModel::SupportsFirstDimBatching(bool* supports)` shouldn't call into the server API as the API may not work properly unless the server is running. FYI, warmup does have batching functionality, so I don't think the current change is a proper fix
> 
> Exactly. SupportsFirstDimBatching can be changed to directly read the max_batch_size from the model config and return true if it is non-zero. @dyastremsky Does that make sense?

It does. Thank you all for your feedback and expertise. I'll update SupportsFirstDimBatching. Once we decide to go with that ticket (different repository), I'll close this one.

2021-12-10 21:33 UTC, CoderHam approved these changes

2021-12-16 01:28 UTC, tanmayv25 commented
@dyastremsky  I think you can close this PR as we are sticking with our earlier function signature for backwards-compatibility.

2021-12-16 01:48 UTC, dyastremsky commented
> @dyastremsky I think you can close this PR as we are sticking with our earlier function signature for backwards-compatibility?

Good point, I'll close it.

2021-12-16 01:48 UTC, closed without merging